### ISSUE TITLE
Small error in URL (link to OpenSCAD Gist)

### ISSUE THREAD

**Issue by golanlevin** [beardicus/awesome-plotters#27]
The link to the Parametric 3d-Printable Plotter Pen Adapter currently has an error. Presently it is: 

```
https://openjscad.org/#https://gist.githubusercontent.com/beardicus/d668c0f6b96be53d16dc/raw/plotter-pen-adapter.jscad
```

It should be: 
```
https://gist.githubusercontent.com/beardicus/d668c0f6b96be53d16dc/raw/plotter-pen-adapter.jscad 
```

Thanks for the great resource!
Best,
Golan

**Comment by beardicus** [comment]
Hi Golan! Alas, the link is correct but the openjscad.org site appears to be down!

(note that this is Open **JS** CAD, not the normal Open **S** CAD)

The link is formatted to open up the Gist directly in OpenJSCAD's web-based viewer, with a nice little GUI for changing some of the parameters and outputting a new STL file. Since this file is Javascript and will only work with the troublesome site and not in OpenSCAD, I'm going to leave this for a day or two to see if the site comes back.

[This thingiverse model](https://www.thingiverse.com/thing:229982) is basically the same parametric file only in plain OpenSCAD format.

Thanks for the note, good luck with your class... I hope the list is useful for your students, and that they feel free to submit any new plotter-related links that they discover!

**Comment by beardicus** [comment]
Thanks again for the heads up. I finally fixed this by updating the code to the new OpenJSCAD style and updating the URL to use openjscad.xyz.
